import { Injectable, signal, computed } from '@angular/core';
import { Observable, of, BehaviorSubject } from 'rxjs';
import { delay } from 'rxjs/operators';
import { Shipment, ShipmentStatus, ShipmentTabFilter } from '../models/shipment.model';

const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 'ORD-1001',
    customerName: 'Ahmed Montage',
    productName: 'Luxury Sofa Set',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=200&fit=crop',
    orderCount: 15,
    weight: 1,
    deliveryDate: '20 OCT - 02:30',
    arrivalDate: '20 OCT 2022',
    orderDate: '15 OCT 2022',
    status: ShipmentStatus.TRANSIT,
    notes: 'This order cannot be controlled by the courier, shipped as set',
    receiverName: 'Abdullah Salman',
    receiverPhone: '+974 5092 7803',
    receiverCity: 'Dubai',
    receiverAddress: 'El-Rhayan, Zone 55, Street 984, Building 781',
    receiverCountry: 'UAE',
    trackingNumber: 'TRK-9988-XXYY',
    category: 'Fades',
    dimensions: { length: 180, width: 90, height: 75 },
    timeline: [
      { label: 'Order Placed', date: '15 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '16 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '18 OCT 2022', completed: true, active: true },
      { label: 'Out for Delivery', date: '20 OCT 2022', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1002',
    customerName: 'Ahmed Montage',
    productName: 'Modern Dining Table',
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=300&h=200&fit=crop',
    orderCount: 13,
    weight: 1,
    deliveryDate: '20 OCT - 02:30',
    arrivalDate: '20 OCT 2022',
    orderDate: '14 OCT 2022',
    status: ShipmentStatus.PREPARATION,
    notes: 'The order has been received from the dealer & placed in the storage',
    receiverName: 'Mohammed Al-Rashid',
    receiverPhone: '+966 5011 2233',
    receiverCity: 'Riyadh',
    receiverAddress: 'Al-Olaya District, King Fahd Road, Building 45',
    receiverCountry: 'Saudi Arabia',
    trackingNumber: 'TRK-8877-AABB',
    category: 'Furniture',
    dimensions: { length: 200, width: 100, height: 76 },
    timeline: [
      { label: 'Order Placed', date: '14 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '15 OCT 2022', completed: true, active: true },
      { label: 'Shipped', date: '--', completed: false, active: false },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1003',
    customerName: 'Ahmed Montage',
    productName: 'Velvet Armchair',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=300&h=200&fit=crop',
    orderCount: 13,
    weight: 1,
    deliveryDate: '20 OCT - 02:30',
    arrivalDate: '20 OCT 2022',
    orderDate: '12 OCT 2022',
    status: ShipmentStatus.DELIVERED,
    notes: 'Handle with care - fragile legs',
    receiverName: 'Sara Al-Mansouri',
    receiverPhone: '+971 5566 7788',
    receiverCity: 'Abu Dhabi',
    receiverAddress: 'Khalifa City A, Street 12, Villa 7',
    receiverCountry: 'UAE',
    trackingNumber: 'TRK-7766-CCDD',
    category: 'Seating',
    dimensions: { length: 80, width: 75, height: 90 },
    timeline: [
      { label: 'Order Placed', date: '12 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '13 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '15 OCT 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '19 OCT 2022', completed: true, active: false },
      { label: 'Delivered', date: '20 OCT 2022', completed: true, active: true },
    ],
  },
  {
    id: 'ORD-1004',
    customerName: 'Ahmed Montage',
    productName: 'King Size Bed Frame',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=300&h=200&fit=crop',
    orderCount: 8,
    weight: 2,
    deliveryDate: '22 OCT - 10:00',
    arrivalDate: '22 OCT 2022',
    orderDate: '10 OCT 2022',
    status: ShipmentStatus.ARRIVED,
    notes: 'Delivery to ground floor only',
    receiverName: 'Khalid Ibrahim',
    receiverPhone: '+973 3322 4455',
    receiverCity: 'Manama',
    receiverAddress: 'Juffair District, Block 338, Road 3803',
    receiverCountry: 'Bahrain',
    trackingNumber: 'TRK-6655-EEFF',
    category: 'Bedroom',
    timeline: [
      { label: 'Order Placed', date: '10 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '11 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '14 OCT 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '22 OCT 2022', completed: true, active: true },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1005',
    customerName: 'Ahmed Montage',
    productName: 'Office Desk Executive',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=300&h=200&fit=crop',
    orderCount: 20,
    weight: 3,
    deliveryDate: '25 OCT - 14:00',
    arrivalDate: '25 OCT 2022',
    orderDate: '08 OCT 2022',
    status: ShipmentStatus.CANCELLED,
    notes: 'Customer requested cancellation',
    receiverName: 'Fatima Al-Zahra',
    receiverPhone: '+965 9988 1122',
    receiverCity: 'Kuwait City',
    receiverAddress: 'Salmiya, Block 12, Street 7, House 3',
    receiverCountry: 'Kuwait',
    trackingNumber: 'TRK-5544-GGHH',
    category: 'Office',
    timeline: [
      { label: 'Order Placed', date: '08 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '--', completed: false, active: false },
      { label: 'Shipped', date: '--', completed: false, active: false },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1006',
    customerName: 'Ahmed Montage',
    productName: 'Bookshelf Unit',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&h=200&fit=crop&sat=-50',
    orderCount: 10,
    weight: 1.5,
    deliveryDate: '18 OCT - 09:00',
    arrivalDate: '18 OCT 2022',
    orderDate: '05 OCT 2022',
    status: ShipmentStatus.DELIVERED,
    notes: 'Assembly included in service',
    receiverName: 'Omar Nasser',
    receiverPhone: '+968 7766 5544',
    receiverCity: 'Muscat',
    receiverAddress: 'Al Khuwair, Block 53, House 12',
    receiverCountry: 'Oman',
    trackingNumber: 'TRK-4433-IIJJ',
    category: 'Storage',
    timeline: [
      { label: 'Order Placed', date: '05 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '06 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '10 OCT 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '17 OCT 2022', completed: true, active: false },
      { label: 'Delivered', date: '18 OCT 2022', completed: true, active: true },
    ],
  },
  {
    id: 'ORD-1007',
    customerName: 'Ahmed Montage',
    productName: 'Recliner Chair Premium',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop',
    orderCount: 5,
    weight: 2,
    deliveryDate: '28 OCT - 11:00',
    arrivalDate: '28 OCT 2022',
    orderDate: '20 OCT 2022',
    status: ShipmentStatus.PREPARATION,
    notes: 'Premium packaging required',
    receiverName: 'Layla Hassan',
    receiverPhone: '+970 5544 3322',
    receiverCity: 'Gaza',
    receiverAddress: 'Al-Rimal, Omar Al-Mukhtar Street, Building 15',
    receiverCountry: 'Palestine',
    trackingNumber: 'TRK-3322-KKLL',
    category: 'Seating',
    timeline: [
      { label: 'Order Placed', date: '20 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '21 OCT 2022', completed: true, active: true },
      { label: 'Shipped', date: '--', completed: false, active: false },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1008',
    customerName: 'Ahmed Montage',
    productName: 'TV Stand Unit',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=300&h=200&fit=crop',
    orderCount: 12,
    weight: 1,
    deliveryDate: '30 OCT - 15:30',
    arrivalDate: '30 OCT 2022',
    orderDate: '22 OCT 2022',
    status: ShipmentStatus.TRANSIT,
    notes: 'Fragile glass panels',
    receiverName: 'Yusuf Al-Qahtani',
    receiverPhone: '+966 5033 9988',
    receiverCity: 'Jeddah',
    receiverAddress: 'Al-Corniche District, Prince Sultan Road, Villa 22',
    receiverCountry: 'Saudi Arabia',
    trackingNumber: 'TRK-2211-MMNN',
    category: 'Living Room',
    timeline: [
      { label: 'Order Placed', date: '22 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '23 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '25 OCT 2022', completed: true, active: true },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1009',
    customerName: 'Ahmed Montage',
    productName: 'Wardrobe 3-Door',
    image: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=300&h=200&fit=crop',
    orderCount: 7,
    weight: 4,
    deliveryDate: '02 NOV - 08:00',
    arrivalDate: '02 NOV 2022',
    orderDate: '24 OCT 2022',
    status: ShipmentStatus.PREPARATION,
    notes: 'Requires 2-person installation team',
    receiverName: 'Nadia Khalil',
    receiverPhone: '+971 5577 8899',
    receiverCity: 'Sharjah',
    receiverAddress: 'Al-Nahda, Industrial Area 12, Building 3',
    receiverCountry: 'UAE',
    trackingNumber: 'TRK-1100-OOPP',
    category: 'Bedroom',
    timeline: [
      { label: 'Order Placed', date: '24 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '25 OCT 2022', completed: true, active: true },
      { label: 'Shipped', date: '--', completed: false, active: false },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1010',
    customerName: 'Ahmed Montage',
    productName: 'Coffee Table Marble',
    image: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=300&h=200&fit=crop',
    orderCount: 18,
    weight: 2.5,
    deliveryDate: '05 NOV - 12:00',
    arrivalDate: '05 NOV 2022',
    orderDate: '26 OCT 2022',
    status: ShipmentStatus.DELIVERED,
    notes: 'Extra padding required for marble top',
    receiverName: 'Hassan Al-Farsi',
    receiverPhone: '+968 9900 1122',
    receiverCity: 'Salalah',
    receiverAddress: 'Al-Hafah District, Block 7, House 34',
    receiverCountry: 'Oman',
    trackingNumber: 'TRK-0099-QQRR',
    category: 'Living Room',
    timeline: [
      { label: 'Order Placed', date: '26 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '27 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '29 OCT 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '04 NOV 2022', completed: true, active: false },
      { label: 'Delivered', date: '05 NOV 2022', completed: true, active: true },
    ],
  },
  {
    id: 'ORD-1011',
    customerName: 'Ahmed Montage',
    productName: 'Floor Lamp Arc Design',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&h=200&fit=crop',
    orderCount: 25,
    weight: 0.5,
    deliveryDate: '08 NOV - 16:00',
    arrivalDate: '08 NOV 2022',
    orderDate: '28 OCT 2022',
    status: ShipmentStatus.ARRIVED,
    notes: 'Electrical item - handle with extreme care',
    receiverName: 'Reem Al-Saad',
    receiverPhone: '+974 6677 8899',
    receiverCity: 'Doha',
    receiverAddress: 'West Bay, Diplomatic Area, Tower 5',
    receiverCountry: 'Qatar',
    trackingNumber: 'TRK-9870-SSTT',
    category: 'Lighting',
    timeline: [
      { label: 'Order Placed', date: '28 OCT 2022', completed: true, active: false },
      { label: 'In Preparation', date: '29 OCT 2022', completed: true, active: false },
      { label: 'Shipped', date: '02 NOV 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '08 NOV 2022', completed: true, active: true },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1012',
    customerName: 'Ahmed Montage',
    productName: 'Outdoor Garden Set',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300&h=200&fit=crop',
    orderCount: 30,
    weight: 5,
    deliveryDate: '10 NOV - 09:30',
    arrivalDate: '10 NOV 2022',
    orderDate: '01 NOV 2022',
    status: ShipmentStatus.TRANSIT,
    notes: 'Outdoor set - weatherproof packaging',
    receiverName: 'Ahmed bin Zayed',
    receiverPhone: '+971 5599 0011',
    receiverCity: 'Al Ain',
    receiverAddress: 'Al Muwaiji District, Street 23, Villa 8',
    receiverCountry: 'UAE',
    trackingNumber: 'TRK-8761-UUVV',
    category: 'Outdoor',
    timeline: [
      { label: 'Order Placed', date: '01 NOV 2022', completed: true, active: false },
      { label: 'In Preparation', date: '02 NOV 2022', completed: true, active: false },
      { label: 'Shipped', date: '05 NOV 2022', completed: true, active: true },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1013',
    customerName: 'Ahmed Montage',
    productName: 'Bathroom Vanity Unit',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=300&h=200&fit=crop',
    orderCount: 9,
    weight: 3,
    deliveryDate: '12 NOV - 11:00',
    arrivalDate: '12 NOV 2022',
    orderDate: '03 NOV 2022',
    status: ShipmentStatus.DELIVERED,
    notes: 'Plumbing pre-installation required',
    receiverName: 'Mariam Al-Hashimi',
    receiverPhone: '+965 6655 4433',
    receiverCity: 'Kuwait City',
    receiverAddress: 'Hawalli, Block 4, Street 2, Building 8',
    receiverCountry: 'Kuwait',
    trackingNumber: 'TRK-7652-WWXX',
    category: 'Bathroom',
    timeline: [
      { label: 'Order Placed', date: '03 NOV 2022', completed: true, active: false },
      { label: 'In Preparation', date: '04 NOV 2022', completed: true, active: false },
      { label: 'Shipped', date: '07 NOV 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '11 NOV 2022', completed: true, active: false },
      { label: 'Delivered', date: '12 NOV 2022', completed: true, active: true },
    ],
  },
  {
    id: 'ORD-1014',
    customerName: 'Ahmed Montage',
    productName: 'Kids Bunk Bed',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop',
    orderCount: 11,
    weight: 2,
    deliveryDate: '15 NOV - 14:00',
    arrivalDate: '15 NOV 2022',
    orderDate: '05 NOV 2022',
    status: ShipmentStatus.PREPARATION,
    notes: 'Safety guards must be installed',
    receiverName: 'Tariq Al-Amri',
    receiverPhone: '+966 5022 3344',
    receiverCity: 'Dammam',
    receiverAddress: 'Al-Shati District, Street 9, House 14',
    receiverCountry: 'Saudi Arabia',
    trackingNumber: 'TRK-6543-YYZZ',
    category: 'Kids',
    timeline: [
      { label: 'Order Placed', date: '05 NOV 2022', completed: true, active: false },
      { label: 'In Preparation', date: '06 NOV 2022', completed: true, active: true },
      { label: 'Shipped', date: '--', completed: false, active: false },
      { label: 'Out for Delivery', date: '--', completed: false, active: false },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
  {
    id: 'ORD-1015',
    customerName: 'Ahmed Montage',
    productName: 'Wall Art Canvas Set',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=300&h=200&fit=crop',
    orderCount: 22,
    weight: 0.3,
    deliveryDate: '17 NOV - 10:00',
    arrivalDate: '17 NOV 2022',
    orderDate: '07 NOV 2022',
    status: ShipmentStatus.ARRIVED,
    notes: 'Do not bend - rigid packaging',
    receiverName: 'Zainab Al-Sayed',
    receiverPhone: '+973 3399 5577',
    receiverCity: 'Riffa',
    receiverAddress: 'Southern Riffa, Block 905, House 2',
    receiverCountry: 'Bahrain',
    trackingNumber: 'TRK-5430-AABB',
    category: 'Decor',
    timeline: [
      { label: 'Order Placed', date: '07 NOV 2022', completed: true, active: false },
      { label: 'In Preparation', date: '08 NOV 2022', completed: true, active: false },
      { label: 'Shipped', date: '11 NOV 2022', completed: true, active: false },
      { label: 'Out for Delivery', date: '17 NOV 2022', completed: true, active: true },
      { label: 'Delivered', date: '--', completed: false, active: false },
    ],
  },
];

@Injectable({ providedIn: 'root' })
export class ShipmentService {
  private readonly _loading = new BehaviorSubject<boolean>(false);
  readonly loading$ = this._loading.asObservable();

  getShipments(): Observable<Shipment[]> {
    this._loading.next(true);
    return of(MOCK_SHIPMENTS).pipe(delay(1200));
  }

  getShipmentById(id: string): Observable<Shipment | undefined> {
    return of(MOCK_SHIPMENTS.find((s) => s.id === id)).pipe(delay(300));
  }
}